In [45]:
print(1)

1

In [46]:
import pandas as pd
import numpy as np

# from google.colab import drive
# drive.mount('/content/gdrive')
# DATA_PATH = '/content/gdrive/MyDrive/REU/PROJECT/DATA/'
MN_PATH = "/home/jovyan/work/ner_congressional_records/"

In [47]:
mn_df = pd.read_csv(MN_PATH+"mn_transactors.csv")
mn_df.head()

/tmp/ipykernel_5934/1267245001.py:1: DtypeWarning: Columns (5,10) have mixed types. Specify dtype option on import or set low_memory=False.
  mn_df = pd.read_csv(MN_PATH+"mn_transactors.csv")

,full_name,last_name,first_name,name_preferred,middle_name,name_suffix,reported_state,id,transactor_type,transactor_type_specific,name
0,Not Employed,NaN,NaN,NaN,NaN,NaN,MN,aaf1c118-9104-42f6-ac05-43a47d2ef232,NaN,NaN,NaN
1,Self employed Sole Proprietor - Hotsprings Hot...,NaN,NaN,NaN,NaN,NaN,MN,a6963a77-cec2-4cda-b347-a4f2fcfb09b0,NaN,NaN,NaN
2,QWEST COMMUNICATIONS,NaN,NaN,NaN,NaN,NaN,MN,3c840d6a-869a-4153-8832-0d2926d0d066,NaN,NaN,NaN
3,Minnesota State,NaN,NaN,NaN,NaN,NaN,MN,0ea1612f-447b-4cb2-874f-cd984a4ba009,NaN,NaN,NaN
4,Seiche,NaN,NaN,NaN,NaN,NaN,MN,2bccc1e7-548b-4466-b64c-784f3224b128,NaN,NaN,NaN

<h1>Transactor types columms
</h1>

In [48]:
mn_df['transactor_type']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
979975    NaN
979976    NaN
979977    NaN
979978    NaN
979979    NaN
Name: transactor_type, Length: 979980, dtype: object

In [49]:
mn_df['transactor_type_specific']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
979975    NaN
979976    NaN
979977    NaN
979978    NaN
979979    NaN
Name: transactor_type_specific, Length: 979980, dtype: object

In [50]:
print("transactor types:", mn_df.transactor_type.unique())
print()
print("transactor type specific:", mn_df.transactor_type_specific.unique())

transactor types: [nan 'Individual' 'Organization' 'Self employed Retired']

transactor type specific: [nan 'Individual' 'Candidate' 'Party' 'Committee' 'Lobbyist'
 'Political Fund' 'Political Committee' 'Independent Expenditure Fund'
 'Independent Expenditure Committee' 'Ballot Fund' 'Ballot Committee']

<h1>Names columns</h1>

In [51]:
mn_df[['full_name', 'last_name', 'first_name', 'name_preferred', 'middle_name', 'name_suffix', 'name']]

,full_name,last_name,first_name,name_preferred,middle_name,name_suffix,name
0,Not Employed,NaN,NaN,NaN,NaN,NaN,NaN
1,Self employed Sole Proprietor - Hotsprings Hot...,NaN,NaN,NaN,NaN,NaN,NaN
2,QWEST COMMUNICATIONS,NaN,NaN,NaN,NaN,NaN,NaN
3,Minnesota State,NaN,NaN,NaN,NaN,NaN,NaN
4,Seiche,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
979975,NaN,NaN,NaN,NaN,NaN,NaN,MediaVista Group
979976,NaN,NaN,NaN,NaN,NaN,NaN,NARAL
979977,NaN,NaN,NaN,NaN,NaN,NaN,No Coast Workshop
979978,NaN,NaN,NaN,NaN,NaN,NaN,Screen Strategies Media
979979,NaN,NaN,NaN,NaN,NaN,NaN,MN Association of Professional Employees

<h1>NaN values</h1>

In [52]:
""""transactor_type == NaN"""
mn_df[mn_df['transactor_type'].isna()].head()

,full_name,last_name,first_name,name_preferred,middle_name,name_suffix,reported_state,id,transactor_type,transactor_type_specific,name
0,Not Employed,NaN,NaN,NaN,NaN,NaN,MN,aaf1c118-9104-42f6-ac05-43a47d2ef232,NaN,NaN,NaN
1,Self employed Sole Proprietor - Hotsprings Hot...,NaN,NaN,NaN,NaN,NaN,MN,a6963a77-cec2-4cda-b347-a4f2fcfb09b0,NaN,NaN,NaN
2,QWEST COMMUNICATIONS,NaN,NaN,NaN,NaN,NaN,MN,3c840d6a-869a-4153-8832-0d2926d0d066,NaN,NaN,NaN
3,Minnesota State,NaN,NaN,NaN,NaN,NaN,MN,0ea1612f-447b-4cb2-874f-cd984a4ba009,NaN,NaN,NaN
4,Seiche,NaN,NaN,NaN,NaN,NaN,MN,2bccc1e7-548b-4466-b64c-784f3224b128,NaN,NaN,NaN

In [53]:
""""transactor_type_specific == NaN"""
mn_df[mn_df['transactor_type_specific'].isna()].head()

,full_name,last_name,first_name,name_preferred,middle_name,name_suffix,reported_state,id,transactor_type,transactor_type_specific,name
0,Not Employed,NaN,NaN,NaN,NaN,NaN,MN,aaf1c118-9104-42f6-ac05-43a47d2ef232,NaN,NaN,NaN
1,Self employed Sole Proprietor - Hotsprings Hot...,NaN,NaN,NaN,NaN,NaN,MN,a6963a77-cec2-4cda-b347-a4f2fcfb09b0,NaN,NaN,NaN
2,QWEST COMMUNICATIONS,NaN,NaN,NaN,NaN,NaN,MN,3c840d6a-869a-4153-8832-0d2926d0d066,NaN,NaN,NaN
3,Minnesota State,NaN,NaN,NaN,NaN,NaN,MN,0ea1612f-447b-4cb2-874f-cd984a4ba009,NaN,NaN,NaN
4,Seiche,NaN,NaN,NaN,NaN,NaN,MN,2bccc1e7-548b-4466-b64c-784f3224b128,NaN,NaN,NaN

In [54]:

# mn_df[mn_df[['transactor_type', 'transactor_type_specific']].isna().all(axis=1)]['transactor_type'].unique()
# mn_df[mn_df[['transactor_type', 'transactor_type_specific']].isna().all(axis=1)]['transactor_type_specific'].unique()

In [ ]:
""""NaN == transactor_type == transactor_type_specific"""

mn_df[mn_df[['transactor_type', 'transactor_type_specific']].isna().all(axis=1)].head()

,full_name,last_name,first_name,name_preferred,middle_name,name_suffix,reported_state,id,transactor_type,transactor_type_specific,name
0,Not Employed,NaN,NaN,NaN,NaN,NaN,MN,aaf1c118-9104-42f6-ac05-43a47d2ef232,NaN,NaN,NaN
1,Self employed Sole Proprietor - Hotsprings Hot...,NaN,NaN,NaN,NaN,NaN,MN,a6963a77-cec2-4cda-b347-a4f2fcfb09b0,NaN,NaN,NaN
2,QWEST COMMUNICATIONS,NaN,NaN,NaN,NaN,NaN,MN,3c840d6a-869a-4153-8832-0d2926d0d066,NaN,NaN,NaN
3,Minnesota State,NaN,NaN,NaN,NaN,NaN,MN,0ea1612f-447b-4cb2-874f-cd984a4ba009,NaN,NaN,NaN
4,Seiche,NaN,NaN,NaN,NaN,NaN,MN,2bccc1e7-548b-4466-b64c-784f3224b128,NaN,NaN,NaN

In [ ]:
""""Nan == full_name == last_name == first_name == name_preferred == middle_name == name_suffix == name"""

mn_df[mn_df[['full_name', 'last_name', 'first_name', 'name_preferred', 'middle_name', 'name_suffix', 'name']].isna().all(axis=1)].head()

,full_name,last_name,first_name,name_preferred,middle_name,name_suffix,reported_state,id,transactor_type,transactor_type_specific,name
1051,NaN,NaN,NaN,NaN,NaN,NaN,MN,0fd662d6-dfb4-4f3f-b3c0-f784f7466202,NaN,NaN,NaN
2494,NaN,NaN,NaN,NaN,NaN,NaN,MN,84605e7f-d85c-4219-ba14-f6977044ebbe,NaN,NaN,NaN
2612,NaN,NaN,NaN,NaN,NaN,NaN,MN,0f518988-2070-44c7-8c69-a94f9a581cc8,NaN,NaN,NaN
4843,NaN,NaN,NaN,NaN,NaN,NaN,MN,dcfdd869-a8af-440d-ae81-70e4a7877c74,NaN,NaN,NaN
5926,NaN,NaN,NaN,NaN,NaN,NaN,MN,97d8d9b7-9c2c-4022-a7e5-3c846040e0f3,NaN,NaN,NaN

In [ ]:
""""NaN == transactor_type == transactor_type_specific == full_name == last_name == first_name == name_preferred == middle_name == name_suffix == name"""
mn_df[mn_df[['full_name', 'last_name', 'first_name', 'name_preferred', 'middle_name', 'name_suffix', 'name','transactor_type', 'transactor_type_specific']].isna().all(axis=1)].head()

,full_name,last_name,first_name,name_preferred,middle_name,name_suffix,reported_state,id,transactor_type,transactor_type_specific,name
1051,NaN,NaN,NaN,NaN,NaN,NaN,MN,0fd662d6-dfb4-4f3f-b3c0-f784f7466202,NaN,NaN,NaN
2494,NaN,NaN,NaN,NaN,NaN,NaN,MN,84605e7f-d85c-4219-ba14-f6977044ebbe,NaN,NaN,NaN
2612,NaN,NaN,NaN,NaN,NaN,NaN,MN,0f518988-2070-44c7-8c69-a94f9a581cc8,NaN,NaN,NaN
4843,NaN,NaN,NaN,NaN,NaN,NaN,MN,dcfdd869-a8af-440d-ae81-70e4a7877c74,NaN,NaN,NaN
5926,NaN,NaN,NaN,NaN,NaN,NaN,MN,97d8d9b7-9c2c-4022-a7e5-3c846040e0f3,NaN,NaN,NaN