In [2]:
DATA_PATH = "/home/jovyan/work/ner_congressional_records/DATA/"
import pandas as pd

In [3]:
print(1)

1

In [4]:
def org_labels(st):
    if st != "Individual" and st != "Candidate":
        return "Organization"
    return "Individual"

In [5]:
df = pd.read_csv(DATA_PATH+"annotated_data.csv")

In [6]:
df['transactor_type'] = df['transactor_type'].apply(org_labels)
df = df[['full_name', 'transactor_type']]

In [7]:
df

                                      full_name transactor_type
0              franklin county reagan coalition    Organization
1              nextgen climate action committee    Organization
2               zarwin baum good government pac    Organization
3       mid-atlantic laborers' political league    Organization
4                             toll bros inc pac    Organization
...                                         ...             ...
518282                           cindy  olofson      Individual
518283                              ryan  olsen      Individual
518284                           andrew  orgill      Individual
518285                            chris  ortega      Individual
518286                           sayona  ortega      Individual

[518287 rows x 2 columns]

In [8]:
from imblearn.under_sampling import RandomUnderSampler

In [9]:

# encode transactor_type as numeric labels
df['label'] = df['transactor_type'].factorize()[0]

# features and target for under-sampling
X = df[['transactor_type']]
y = df['label']

# apply random under-sampling to balance the classes
rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(X, y)

# # merge resampled data with full original data
# df_resampled = pd.merge(
#     pd.concat([X_resampled, y_resampled.rename("label")], axis=1),
#     df[['full_name', 'transactor_type']],
#     on=['transactor_type'],
#     how='left'
# ).drop_duplicates().reset_index(drop=True)

# print class distribution and sample data
# print("Balanced transactor_type counts:")
# print(df_resampled['transactor_type'].value_counts())

# print("Sample of cleaned and balanced data:")
# print(df_resampled[['full_name', 'transactor_type']].head())

In [24]:
type(X_resampled['transactor_type'])

pandas.core.series.Series

In [25]:
y_resampled

0         0
1         0
2         0
3         0
4         0
         ..
189686    1
87238     1
452854    1
485998    1
441181    1
Name: label, Length: 153262, dtype: int64

In [ ]:
new_df = pd.concat([X_resampled, y_resampled], axis=1)

       transactor_type  label
0         Organization      0
1         Organization      0
2         Organization      0
3         Organization      0
4         Organization      0
...                ...    ...
189686      Individual      1
87238       Individual      1
452854      Individual      1
485998      Individual      1
441181      Individual      1

[153262 rows x 2 columns]

In [26]:
pd.merge(new_df, df, on='transactor_type')

:

:

: