In [259]:
import pandas as pd
import numpy as np
print(1)
from google.colab import drive
drive.mount('/content/gdrive')
DATA_PATH = '/content/gdrive/MyDrive/REU/PROJECT/DATA/'
# DATA_PATH = "/home/jovyan/work/ner_congressional_records/DATA/"

1
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [260]:
# annotated_data.csv?
# import different csvs and then concat??
pa_transactors = pd.read_csv(DATA_PATH+"pa_transactors_clean.csv")
pa_annotated = pd.read_csv(DATA_PATH+"pa_transactor_annotaded_clean.csv")

/tmp/ipython-input-260-2319438018.py:3: DtypeWarning: Columns (5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  pa_transactors = pd.read_csv(DATA_PATH+"pa_transactors_clean.csv")

In [261]:
pa_transactors.groupby(by='transactor_type', dropna=False).size()
annotated = pa_transactors[pa_transactors['transactor_type'].notna()].copy()
pa_annotated.groupby(by='transactor_type', dropna=False).size()

transactor_type
Candidate    1952
Committee    8173
dtype: int64

In [262]:
annotated = annotated[['full_name', 'transactor_type']].copy()

In [263]:
annotated.rename(columns={'transactor_type': 'label'}, inplace=True)

In [264]:
annotated

                                     full_name      label
2789          franklin county reagan coalition  Committee
2790          nextgen climate action committee  Committee
2791           zarwin baum good government pac  Committee
2792   mid-atlantic laborers' political league  Committee
2793                         toll bros inc pac  Committee
...                                        ...        ...
26436                         joseph l. sackor  Candidate
26437                         young, regina g.  Candidate
26438                            joseph sackor  Candidate
26439                         jordan a. harris  Candidate
26440                 friends of fredda maddox  Committee

[10078 rows x 2 columns]

In [265]:
def convert_bool(input_label):
    '''Converts to numerical encoding'''
    if input_label == 'Candidate' or input_label == 'Individual':
        return 1
    else:
        return 0

# encode transactor_type as numeric labels
annotated['label'] = np.vectorize(convert_bool)(annotated['label'])

In [266]:
annotated

                                     full_name  label
2789          franklin county reagan coalition      0
2790          nextgen climate action committee      0
2791           zarwin baum good government pac      0
2792   mid-atlantic laborers' political league      0
2793                         toll bros inc pac      0
...                                        ...    ...
26436                         joseph l. sackor      1
26437                         young, regina g.      1
26438                            joseph sackor      1
26439                         jordan a. harris      1
26440                 friends of fredda maddox      0

[10078 rows x 2 columns]

In [267]:
pa_annotated = pa_annotated[['full_name', 'transactor_type']].copy()

In [268]:
pa_annotated.rename(columns={"transactor_type":'label'}, inplace=True)

In [269]:
pa_annotated
# encode transactor_type as numeric labels
pa_annotated['label'] = np.vectorize(convert_bool)(pa_annotated['label'])

In [270]:
pa_annotated

                                     full_name  label
0             franklin county reagan coalition      0
1             nextgen climate action committee      0
2              zarwin baum good government pac      0
3      mid-atlantic laborers' political league      0
4                            toll bros inc pac      0
...                                        ...    ...
10120                         joseph l. sackor      1
10121                         young, regina g.      1
10122                            joseph sackor      1
10123                         jordan a. harris      1
10124                 friends of fredda maddox      0

[10125 rows x 2 columns]

In [271]:
ANNOTATED_PA_AZ_FINAL = pd.concat([annotated, pa_annotated])

In [272]:
ANNOTATED_PA_AZ_FINAL.to_csv("pa_annotated_FINAL.csv")

In [273]:
ANNOTATED_PA_AZ_FINAL

                                     full_name  label
2789          franklin county reagan coalition      0
2790          nextgen climate action committee      0
2791           zarwin baum good government pac      0
2792   mid-atlantic laborers' political league      0
2793                         toll bros inc pac      0
...                                        ...    ...
10120                         joseph l. sackor      1
10121                         young, regina g.      1
10122                            joseph sackor      1
10123                         jordan a. harris      1
10124                 friends of fredda maddox      0

[20203 rows x 2 columns]

In [274]:
az_df = pd.read_csv(DATA_PATH+"az_transactors_clean.csv")

In [275]:
az_df

,Unnamed: 0,id,transactor_type,last_name,first_name,middle_name,name_suffix,full_name
0,0,-7,Company,Multiple Vendors,NaN,NaN,NaN,multiple vendors
1,1,-5,Committee,Previous/Next Committee,NaN,NaN,NaN,previous/next committee
2,2,-3,Company,Arizona Secretary of State,NaN,NaN,NaN,arizona secretary of state
3,3,-2,Company,Citizens Clean Election Commission,NaN,NaN,NaN,citizens clean election commission
4,4,-1,Individual,Multiple Contributors,NaN,NaN,NaN,multiple contributors
...,...,...,...,...,...,...,...,...
631006,1048568,1600705,Individual,OLOFSON,CINDY,NaN,NaN,cindy olofson
631007,1048569,1600706,Individual,Olsen,RYAN,NaN,NaN,ryan olsen
631008,1048570,1600707,Individual,ORGILL,ANDREW,NaN,NaN,andrew orgill
631009,1048572,1600709,Individual,ORTEGA,CHRIS,NaN,NaN,chris ortega
631010,1048573,1600710,Individual,Ortega,SAYONA,NaN,NaN,sayona ortega

In [276]:
az_df.groupby(by="transactor_type", dropna=False).size()

transactor_type
Committee      22205
Company        46281
Individual    439707
Party             75
NaN           122743
dtype: int64

In [277]:

az_df_annotated = az_df[az_df['transactor_type'].notna()].copy()

In [278]:
az_df_annotated

,Unnamed: 0,id,transactor_type,last_name,first_name,middle_name,name_suffix,full_name
0,0,-7,Company,Multiple Vendors,NaN,NaN,NaN,multiple vendors
1,1,-5,Committee,Previous/Next Committee,NaN,NaN,NaN,previous/next committee
2,2,-3,Company,Arizona Secretary of State,NaN,NaN,NaN,arizona secretary of state
3,3,-2,Company,Citizens Clean Election Commission,NaN,NaN,NaN,citizens clean election commission
4,4,-1,Individual,Multiple Contributors,NaN,NaN,NaN,multiple contributors
...,...,...,...,...,...,...,...,...
631006,1048568,1600705,Individual,OLOFSON,CINDY,NaN,NaN,cindy olofson
631007,1048569,1600706,Individual,Olsen,RYAN,NaN,NaN,ryan olsen
631008,1048570,1600707,Individual,ORGILL,ANDREW,NaN,NaN,andrew orgill
631009,1048572,1600709,Individual,ORTEGA,CHRIS,NaN,NaN,chris ortega
631010,1048573,1600710,Individual,Ortega,SAYONA,NaN,NaN,sayona ortega

In [279]:
az_df_annotated = az_df_annotated[['full_name', 'transactor_type']]

In [280]:
az_df_annotated.rename(columns={"transactor_type":"label"}, inplace=True)

/tmp/ipython-input-280-1529640429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  az_df_annotated.rename(columns={"transactor_type":"label"}, inplace=True)

In [281]:
az_df_annotated['label'] = np.vectorize(convert_bool)(az_df_annotated['label'])

/tmp/ipython-input-281-133276056.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  az_df_annotated['label'] = np.vectorize(convert_bool)(az_df_annotated['label'])

In [282]:
az_df_annotated.to_csv("az_annotated_FINAL.csv")

In [283]:
az_df_annotated

                                 full_name  label
0                         multiple vendors      0
1                  previous/next committee      0
2               arizona secretary of state      0
3       citizens clean election commission      0
4                    multiple contributors      1
...                                    ...    ...
631006                      cindy  olofson      1
631007                         ryan  olsen      1
631008                      andrew  orgill      1
631009                       chris  ortega      1
631010                      sayona  ortega      1

[508268 rows x 2 columns]

In [284]:

mn_annotated = pd.read_csv(DATA_PATH+'mn_annotated_data.csv')
mi_annotated = pd.read_csv(DATA_PATH+'mi_annotated_data.csv')

In [285]:
mn_annotated.groupby(by='label', dropna=False).size()

label
0     2770
1    71785
dtype: int64

In [286]:
mi_annotated.groupby(by='label', dropna=False).size()

label
0    2086
dtype: int64

In [287]:
pa_undersampled = pd.read_csv(DATA_PATH+"undersampled_pa_annotated_FINAL.csv")
az_undersampled = pd.read_csv(DATA_PATH+"undersampled_az_annotated_FINAL.csv")
mn_undersampled = pd.read_csv(DATA_PATH+"undersampled_mn_annotated_data.csv")
mi_undersampled = pd.read_csv(DATA_PATH+"undersampled_mi_annotated_data.csv")

In [288]:
aux = pd.concat([pa_undersampled, az_undersampled, mn_undersampled, mi_undersampled])

In [289]:
aux = aux.drop('Unnamed: 0', axis=1)

In [290]:
aux

                                       full_name  label
0     citizens for stan saylor c/o brenda s resh      0
1                                 iezzi, linda        1
2                                     john flood      1
3                                  pa united pac      0
4                                weaver,linda j       1
...                                          ...    ...
2077                       meerman majority fund      0
2078                                     mac pac      0
2079                    friends of matt hall pac      0
2080                    cte lily cheng schulting      0
2081                                   vote mama      0

[16656 rows x 2 columns]

In [291]:
X = aux['full_name'].copy()

In [292]:
X = X.copy()

In [293]:
y = aux['label'].copy()

In [309]:
aux[aux['full_name'].isna()]

Empty DataFrame
Columns: [full_name, label]
Index: []

In [314]:
az_df_annotated[az_df_annotated['full_name'].isna()]

       full_name  label
229473       NaN      0

In [295]:
# all the data that is not on any of the undersampled dataframes
test_set = pd.concat([aux,mi_annotated, mn_annotated, az_df_annotated,ANNOTATED_PA_AZ_FINAL]).drop_duplicates(keep=False)

In [296]:
test_set = test_set.drop('Unnamed: 0', axis=1)

In [297]:
X = X.to_frame()
y = y.to_frame()

In [298]:
type(X)

pandas.core.frame.DataFrame

In [299]:
test_set

                                               full_name  label
0                  retired peoples political action fund      0
1      blake blake richard house committee blake rich...      1
2                                       daniel, holmberg      1
3                     stebbins, marianne house committee      0
4                                         gasperini, jim      1
...                                                  ...    ...
10018                                squilla for council      0
10038                                        costa, paul      0
10039                                     molchany, erin      0
10045                                     payne, john d.      0
10107                                      taiba sultana      1

[586845 rows x 2 columns]

In [300]:
from sklearn.model_selection import train_test_split

# stratify = y???
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.20, random_state=24)

In [301]:
type(y_train)

pandas.core.frame.DataFrame

In [302]:
train_set = X_train.copy()
train_set['label'] = y_train

In [303]:
train_set

                                              full_name  label
778                            iaff firepac non-federal      0
678                                         he, ruirong      1
4597  uwua local 686 committee political education fund      0
2644                                       ann  corkery      1
3687                    st. cloud education association      0
...                                                 ...    ...
2695                                 mcilquham, barbara      1
1642                                       dan williams      0
4812                           59th senate district rpm      0
899   exxon mobil coporation pac                    ...      0
2990                                  gough, christabel      1

[13324 rows x 2 columns]

In [304]:
val_set = X_val.copy()
val_set['label'] = y_val

In [305]:
val_set

                                 full_name  label
2835                       daniel  calihan      1
1523  cte benjamin a. schock for probate c      0
3332                            paul friel      1
362                       leon a. king, ii      1
3506                        timothy barker      1
...                                    ...    ...
4713                     elizabeth fiedler      1
2742                       zachari halkias      1
4132                       precinct 12 dfl      0
1601                   mccutchen, courtney      1
2490                  cozzone, kathleen m       1

[3332 rows x 2 columns]

In [306]:
test_set.to_csv("test-all-states.csv")
train_set.to_csv("train-undersampled-all-states.csv")
val_set.to_csv("validation-undersampled-all-states.csv")