In [ ]:
import pandas as pd
import numpy as np

DATA_PATH = "/home/jovyan/work/ner_congressional_records/DATA/"

<h1>UNCOMMENT THIS WHILE USING COLLAB</h1>

In [ ]:

# from google.colab import drive
# drive.mount('/content/gdrive')
# DATA_PATH = '/content/gdrive/MyDrive/REU/PROJECT/DATA/'

<h1>TRANSACTOR TYPES (CLASSES)</h1>

In [87]:
transactor_types = {
    0: 'Individual',
    1: 'Committee',
    2: 'Company',
    3: 'Party',
}

<h1>PA_TRANSACTORS CSV</h1>

In [88]:
pa_transcators =  pd.read_csv(DATA_PATH+"pa_transactors.csv")
pa_transcators

/tmp/ipykernel_19157/2784178402.py:1: DtypeWarning: Columns (4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  pa_transcators =  pd.read_csv(DATA_PATH+"pa_transactors.csv")

,Unnamed: 0,id,full_name,reported_state,transactor_type,party,phone_number
0,0,8a2df1b3-1ffe-4922-a23e-fefe7cc2ce31,Eli Lilly and Company,PA,NaN,NaN,NaN
1,211,58ebe6de-14fc-4d59-ab12-127ef3615a6d,HDR INC,PA,NaN,NaN,NaN
2,212,9312a5f1-5038-47d1-be0d-ace089d223ca,Ms Lisa A Collie-Pittman,PA,NaN,NaN,NaN
3,213,e4e0aadc-d0e5-4549-bd3e-ffcb77cb4e62,Mrs Kathleen C Solotkin,PA,NaN,NaN,NaN
4,214,da50cf52-f4f1-486b-8d1c-4e1015e98719,Mr Mitchell Silverstein,PA,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1001140,4063818,d4cb91f0-be3b-48ff-85a6-68fe255e03e2,ACH Vantiv,PA,NaN,NaN,NaN
1001141,4063835,bedc5b16-caf0-46db-bdcb-a10651b7cbca,ACT BLUE LLC,PA,NaN,NaN,NaN
1001142,4063836,927f97aa-f338-4a44-879e-cc09576a3530,24HourWristbands,PA,NaN,NaN,NaN
1001143,4063861,44fbaef3-55df-44c0-a9d9-e85b38f8c7f0,ACT BLUE DONATE SERVICE,PA,NaN,NaN,NaN
1001144,4063891,ba516c6a-b491-49e6-9e07-94d810e4d69f,ACT BLUE SERVICE FEES,PA,NaN,NaN,NaN

<h1>AZ_TRANSACTORS CSV</h1>

In [89]:
az_transcators =  pd.read_csv(DATA_PATH+"/az_transactors.csv")

az_transcators

,id,transactor_type,last_name,first_name,middle_name,name_suffix
0,-7,Company,Multiple Vendors,NaN,NaN,NaN
1,-5,Committee,Previous/Next Committee,NaN,NaN,NaN
2,-3,Company,Arizona Secretary of State,NaN,NaN,NaN
3,-2,Company,Citizens Clean Election Commission,NaN,NaN,NaN
4,-1,Individual,Multiple Contributors,NaN,NaN,NaN
...,...,...,...,...,...,...
1048570,1600707,Individual,ORGILL,ANDREW,NaN,NaN
1048571,1600708,Individual,OROZCO,LAURA,NaN,NaN
1048572,1600709,Individual,ORTEGA,CHRIS,NaN,NaN
1048573,1600710,Individual,Ortega,SAYONA,NaN,NaN
1048574,1600711,Individual,ORTIZ,DAVID,NaN,NaN

<h1>PA_TRANSACTOR_ANNOTATED CSV</h1>

In [90]:
pa_transcator_annotated =  pd.read_csv(DATA_PATH+"pa_transactor_annotated.csv")
pa_transcator_annotated.sort_values(by='full_name')
# pa_transcator_annotated.sort_values(by='party')

,Unnamed: 0,id,full_name,reported_state,transactor_type,party,phone_number
58127,83377,e4a89361-bfe0-4d11-80c1-2f69e0e80c6f,CITIZENS FOR BOYLE,PA,Committee,Democratic Party,NaN
56501,81751,e4a89361-bfe0-4d11-80c1-2f69e0e80c6f,CITIZENS FOR BOYLE,PA,Committee,Democratic Party,NaN
51003,76062,8bdaf5d7-547a-4416-bfae-92d77a3befb4,"MAUCK, SHAWN C",PA,Candidate,Democratic Party,NaN
49377,74388,cd06d2ae-6985-4073-8cfe-130058e3b246,(BOWL PAC),PA,Committee,NaN,7172325322
21980,33257,0030b525-672f-447c-ab87-d6b1ef2b34c1,(OTO PAC),PA,Committee,NaN,7172325322
...,...,...,...,...,...,...,...
6773,9920,bd4ca73b-09ed-4915-a24c-1d7d9145ecbe,maguire pa pac,PA,Committee,NaN,NaN
5890,9011,bd4ca73b-09ed-4915-a24c-1d7d9145ecbe,maguire pa pac,PA,Committee,NaN,NaN
24163,35489,bd4ca73b-09ed-4915-a24c-1d7d9145ecbe,maguire pa pac,PA,Committee,NaN,NaN
5758,8879,bd4ca73b-09ed-4915-a24c-1d7d9145ecbe,maguire pa pac,PA,Committee,NaN,NaN
3119,6214,bd4ca73b-09ed-4915-a24c-1d7d9145ecbe,maguire pa pac,PA,Committee,NaN,NaN

In [93]:
pa_transcators[pa_transcators['full_name'].isna()]

,Unnamed: 0,id,full_name,reported_state,transactor_type,party,phone_number
14397,54449,83708f03-7052-4a7e-84a8-b69569c1a36b,NaN,PA,NaN,NaN,NaN

In [94]:
pa_transcator_annotated[pa_transcator_annotated['full_name'].isna()]

Empty DataFrame
Columns: [Unnamed: 0, id, full_name, reported_state, transactor_type, party, phone_number]
Index: []

<h1>JOIN NAMES COLUMNS ON NEW COLUMN 'full_name'.
<h1>

In [95]:
az_transcators['full_name'] = az_transcators['name_suffix'].astype(str) + ' ' + az_transcators['first_name'].astype(str) + ' ' + az_transcators['middle_name'].astype(str) + ' ' + az_transcators['last_name'].astype(str)

In [96]:
az_transcators['full_name'] = az_transcators['full_name'].str.replace('nan', '', regex=False).str.strip()

In [116]:
az_transcators

,id,transactor_type,last_name,first_name,middle_name,name_suffix,full_name
0,-7,Company,Multiple Vendors,NaN,NaN,NaN,Multiple Vendors
1,-5,Committee,Previous/Next Committee,NaN,NaN,NaN,Previous/Next Committee
2,-3,Company,Arizona Secretary of State,NaN,NaN,NaN,Arizona Secretary of State
3,-2,Company,Citizens Clean Election Commission,NaN,NaN,NaN,Citizens Clean Election Commission
4,-1,Individual,Multiple Contributors,NaN,NaN,NaN,Multiple Contributors
...,...,...,...,...,...,...,...
1048570,1600707,Individual,ORGILL,ANDREW,NaN,NaN,ANDREW ORGILL
1048571,1600708,Individual,OROZCO,LAURA,NaN,NaN,LAURA OROZCO
1048572,1600709,Individual,ORTEGA,CHRIS,NaN,NaN,CHRIS ORTEGA
1048573,1600710,Individual,Ortega,SAYONA,NaN,NaN,SAYONA Ortega
1048574,1600711,Individual,ORTIZ,DAVID,NaN,NaN,DAVID ORTIZ

<h1>MISSING DATA METRICS</h1>

In [99]:
az_transcators.isna().mean()*100

id                  0.000000
transactor_type    14.736190
last_name           0.003147
first_name         11.642658
middle_name        78.407076
name_suffix        97.766874
full_name           0.000000
dtype: float64

In [100]:
pa_transcators.isna().mean()*100

Unnamed: 0          0.000000
id                  0.000000
full_name           0.000100
reported_state      0.000000
transactor_type    98.937117
party              99.520849
phone_number       99.310390
dtype: float64

In [101]:
pa_transcator_annotated.isna().mean()*100

Unnamed: 0          0.000000
id                  0.000000
full_name           0.000000
reported_state      0.000000
transactor_type     0.000000
party              64.055006
phone_number       50.164347
dtype: float64

<h1>DUPLICATE VALUES</h1>
<a href='https://stackoverflow.com/questions/12497402/remove-duplicates-by-columns-a-keeping-the-row-with-the-highest-value-in-column'>REFERENCE</a>

In [102]:
pa_transcators.nunique()

Unnamed: 0         1001145
id                  997050
full_name          1001144
reported_state           1
transactor_type          3
party                    4
phone_number          4272
dtype: int64

In [103]:
pa_transcators

,Unnamed: 0,id,full_name,reported_state,transactor_type,party,phone_number
0,0,8a2df1b3-1ffe-4922-a23e-fefe7cc2ce31,Eli Lilly and Company,PA,NaN,NaN,NaN
1,211,58ebe6de-14fc-4d59-ab12-127ef3615a6d,HDR INC,PA,NaN,NaN,NaN
2,212,9312a5f1-5038-47d1-be0d-ace089d223ca,Ms Lisa A Collie-Pittman,PA,NaN,NaN,NaN
3,213,e4e0aadc-d0e5-4549-bd3e-ffcb77cb4e62,Mrs Kathleen C Solotkin,PA,NaN,NaN,NaN
4,214,da50cf52-f4f1-486b-8d1c-4e1015e98719,Mr Mitchell Silverstein,PA,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1001140,4063818,d4cb91f0-be3b-48ff-85a6-68fe255e03e2,ACH Vantiv,PA,NaN,NaN,NaN
1001141,4063835,bedc5b16-caf0-46db-bdcb-a10651b7cbca,ACT BLUE LLC,PA,NaN,NaN,NaN
1001142,4063836,927f97aa-f338-4a44-879e-cc09576a3530,24HourWristbands,PA,NaN,NaN,NaN
1001143,4063861,44fbaef3-55df-44c0-a9d9-e85b38f8c7f0,ACT BLUE DONATE SERVICE,PA,NaN,NaN,NaN
1001144,4063891,ba516c6a-b491-49e6-9e07-94d810e4d69f,ACT BLUE SERVICE FEES,PA,NaN,NaN,NaN

In [104]:
pa_transcators.groupby(by='id').count().sort_values('full_name')

,Unnamed: 0,full_name,reported_state,transactor_type,party,phone_number
id,,,,,,
83708f03-7052-4a7e-84a8-b69569c1a36b,1,0,1,0,0,0
00000517-5135-4841-9077-c22edc05c83a,1,1,1,0,0,0
aa5ccad9-5d34-4a1a-8b97-05a88c6b8521,1,1,1,0,0,0
aa5ccbc1-54c2-423e-b117-125fb8ac95a4,1,1,1,0,0,0
aa5ccef9-6d1b-44c2-8e54-452295571561,1,1,1,0,0,0
...,...,...,...,...,...,...
aacf3869-b91a-4408-bd97-16b483648b89,17,17,17,17,0,15
6926d097-ccb5-4490-8be8-5266eb26aaa8,17,17,17,17,12,17
845cd9ca-ceae-4516-8a16-6ea2a5a3c67d,20,20,20,20,0,20
fef41338-00ef-4720-8cb4-efa70abb9d65,21,21,21,21,0,21
2cf66f07-e70c-4470-80c0-160a671d852d,28,28,28,28,0,23

In [105]:
pa_transcators.drop_duplicates( subset='id', inplace=True)

In [106]:
pa_transcators.groupby(by='id').count().sort_values('full_name')

,Unnamed: 0,full_name,reported_state,transactor_type,party,phone_number
id,,,,,,
83708f03-7052-4a7e-84a8-b69569c1a36b,1,0,1,0,0,0
aa73d4c0-032c-415f-b615-0ab051fc8160,1,1,1,0,0,0
aa73f538-4577-4a97-ab0f-74aa883ddb09,1,1,1,0,0,0
aa740bf2-5335-4359-9047-07edbceae014,1,1,1,0,0,0
aa741174-2207-4c34-a807-76d076c9d890,1,1,1,0,0,0
...,...,...,...,...,...,...
55609f13-8160-4902-b61b-a98fe5fa0f70,1,1,1,0,0,0
5560a098-5608-42a3-b1b2-36e113ee97d7,1,1,1,0,0,0
5560a23d-3ef4-4e70-969c-136f0e7d363d,1,1,1,0,0,0
555e0a99-a3c7-447e-ae95-7d49b94974b6,1,1,1,0,0,0
fffffd17-21df-4c91-bd2f-496318229e49,1,1,1,0,0,0

In [107]:
pa_transcators

,Unnamed: 0,id,full_name,reported_state,transactor_type,party,phone_number
0,0,8a2df1b3-1ffe-4922-a23e-fefe7cc2ce31,Eli Lilly and Company,PA,NaN,NaN,NaN
1,211,58ebe6de-14fc-4d59-ab12-127ef3615a6d,HDR INC,PA,NaN,NaN,NaN
2,212,9312a5f1-5038-47d1-be0d-ace089d223ca,Ms Lisa A Collie-Pittman,PA,NaN,NaN,NaN
3,213,e4e0aadc-d0e5-4549-bd3e-ffcb77cb4e62,Mrs Kathleen C Solotkin,PA,NaN,NaN,NaN
4,214,da50cf52-f4f1-486b-8d1c-4e1015e98719,Mr Mitchell Silverstein,PA,NaN,NaN,NaN
...,...,...,...,...,...,...,...
1001140,4063818,d4cb91f0-be3b-48ff-85a6-68fe255e03e2,ACH Vantiv,PA,NaN,NaN,NaN
1001141,4063835,bedc5b16-caf0-46db-bdcb-a10651b7cbca,ACT BLUE LLC,PA,NaN,NaN,NaN
1001142,4063836,927f97aa-f338-4a44-879e-cc09576a3530,24HourWristbands,PA,NaN,NaN,NaN
1001143,4063861,44fbaef3-55df-44c0-a9d9-e85b38f8c7f0,ACT BLUE DONATE SERVICE,PA,NaN,NaN,NaN
1001144,4063891,ba516c6a-b491-49e6-9e07-94d810e4d69f,ACT BLUE SERVICE FEES,PA,NaN,NaN,NaN

In [108]:
pa_transcators[pa_transcators['id'] == '845cd9ca-ceae-4516-8a16-6ea2a5a3c67d']

,Unnamed: 0,id,full_name,reported_state,transactor_type,party,phone_number
3219,3502,845cd9ca-ceae-4516-8a16-6ea2a5a3c67d,WESTERN PA LABORERS' PAC,PA,Committee,NaN,4123911712

In [109]:
az_transcators['id'].nunique()

1048575

In [110]:
az_transcators

,id,transactor_type,last_name,first_name,middle_name,name_suffix,full_name
0,-7,Company,Multiple Vendors,NaN,NaN,NaN,Multiple Vendors
1,-5,Committee,Previous/Next Committee,NaN,NaN,NaN,Previous/Next Committee
2,-3,Company,Arizona Secretary of State,NaN,NaN,NaN,Arizona Secretary of State
3,-2,Company,Citizens Clean Election Commission,NaN,NaN,NaN,Citizens Clean Election Commission
4,-1,Individual,Multiple Contributors,NaN,NaN,NaN,Multiple Contributors
...,...,...,...,...,...,...,...
1048570,1600707,Individual,ORGILL,ANDREW,NaN,NaN,ANDREW ORGILL
1048571,1600708,Individual,OROZCO,LAURA,NaN,NaN,LAURA OROZCO
1048572,1600709,Individual,ORTEGA,CHRIS,NaN,NaN,CHRIS ORTEGA
1048573,1600710,Individual,Ortega,SAYONA,NaN,NaN,SAYONA Ortega
1048574,1600711,Individual,ORTIZ,DAVID,NaN,NaN,DAVID ORTIZ

In [111]:
pa_transcator_annotated.groupby(by='id').count().sort_values('full_name')

,Unnamed: 0,full_name,reported_state,transactor_type,party,phone_number
id,,,,,,
d98eccfc-89a4-46e5-a480-9515a6dd99fb,1,1,1,1,0,1
214ba941-12e8-4847-8bc8-a0c38040f881,1,1,1,1,1,1
7dd3490a-f88c-4ed0-8695-731503b8ca91,1,1,1,1,1,1
7ddbec36-9dbc-4a8c-aa9b-35a7a45eae03,1,1,1,1,1,0
5c98f3ac-de3f-4ab6-a147-0d21b80e5842,1,1,1,1,1,1
...,...,...,...,...,...,...
2e4d9a00-7fbf-41bc-9b8b-f561f6850e6b,60,60,60,60,2,0
e24ebc1c-3376-479f-99dc-ccad7f88412c,61,61,61,61,0,0
0dd4a30b-b088-4fa0-b2d0-9f0475a13dc7,66,66,66,66,1,66
a832f2e7-6e23-474a-a235-9252cb0b5d82,71,71,71,71,0,0
ec51614e-b1e4-4d43-aa45-f3ef2eac0012,79,79,79,79,59,55

In [112]:
pa_transcator_annotated[pa_transcator_annotated['id'] == 'ec51614e-b1e4-4d43-aa45-f3ef2eac0012']

,Unnamed: 0,id,full_name,reported_state,transactor_type,party,phone_number
2266,5361,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,Democratic Party,7179208470
2714,5809,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,Democratic Party,7179208470
2804,5899,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,Democratic Party,7179208470
3287,6382,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA DEMOCRATIC PARTY ...,PA,Committee,NaN,NaN
3468,6563,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,Democratic Party,7179208470
...,...,...,...,...,...,...,...
51049,76108,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,Democratic Party,7179208470
53963,79075,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,Democratic Party,7179208470
57304,82554,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,NaN,7179208470
58209,83459,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,NaN,7179208470
59238,89331,ec51614e-b1e4-4d43-aa45-f3ef2eac0012,PA Democratic Party,PA,Committee,NaN,7179208470

In [113]:
pa_transcator_annotated.drop_duplicates( subset='id', inplace=True)

In [114]:
pa_transcator_annotated.groupby(by='id').count().sort_values('full_name')

,Unnamed: 0,full_name,reported_state,transactor_type,party,phone_number
id,,,,,,
000486ed-368c-4600-8d98-7c48bd306737,1,1,1,1,1,0
aa5fe4b5-4da9-483f-8c61-c89da6b790ce,1,1,1,1,1,0
aa54f9f9-f00a-4190-b582-d42371836072,1,1,1,1,1,0
aa50738f-f7a6-4114-ba2d-ca46df8875f7,1,1,1,1,1,1
aa4b5337-bbe8-4cc9-872f-13724d18c915,1,1,1,1,1,0
...,...,...,...,...,...,...
55c5670f-f69d-4cf7-b95e-92e6af9347c8,1,1,1,1,0,0
55c2d3a2-6179-4ee0-be1b-cf927129c07c,1,1,1,1,0,1
55b1ef5a-f921-4826-8ea4-944cfca1e564,1,1,1,1,1,0
54afb64f-b799-46e3-9be4-d6bae66ede0c,1,1,1,1,0,0
fff99d8c-59d5-4aaf-ab11-1a154e984494,1,1,1,1,1,1