In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
tx = pd.read_parquet('/content/drive/MyDrive/DSSI/NER Data/tx_transactors.parquet')

In [ ]:
def merge_name(row):

  if str(row['full_name']) != '<NA>':
    # print('name_preferred', type(row['name_preferred']))
    return row['full_name'].lower()
  elif str(row['name_preferred']) != '<NA>':
    # print('full_name', type(row['full_name']))
    return row['name_preferred'].lower()
  else:
    # print("else")
    name= str(row['first_name']) + ' ' + str(row['last_name'])
    name = name.replace('<NA>','').replace('  ',' ').strip().lower()
    return name

In [ ]:
tx['clean_name'] = tx.apply(merge_name, axis=1)

In [ ]:
tx

,full_name,reported_state,id,transactor_type,last_name,name_suffix,first_name,name_prefix,name_preferred,ein,transactor_type_specific,phone_number,clean_name
0,Not Employed,TX,07be7f88-ef31-4221-91ef-2066b8cfc2eb,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,not employed
1,Self-Employed,TX,d2f3765c-56e5-4edf-b932-5c89db2b166c,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,self-employed
2,Assist2Sell,TX,4b447a14-8217-4529-b2db-c3a5e9aef780,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,assist2sell
3,Distinctionjewelry.Com,TX,e4d83073-528b-41e5-878b-73e8151ab5dc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,distinctionjewelry.com
4,Hendrick Health System,TX,b5f1c50d-86a8-4c48-a3c6-c0f704e2780e,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,hendrick health system
...,...,...,...,...,...,...,...,...,...,...,...,...,...
18066824,Sirloin Stockade,TX,60fdbc9e-479a-4a1b-bc2e-01d555902aee,Organization,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,sirloin stockade
18066825,Logan's Roadhouse,TX,60fdbc9e-479a-4a1b-bc2e-01d555902aee,Organization,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,logan's roadhouse
18066826,Tuscany Market,TX,60fdbc9e-479a-4a1b-bc2e-01d555902aee,Organization,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,tuscany market
18066827,Williamson County Republican Women,TX,60fdbc9e-479a-4a1b-bc2e-01d555902aee,Organization,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,williamson county republican women
18066828,Broaddus Chevron,TX,60fdbc9e-479a-4a1b-bc2e-01d555902aee,Organization,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,broaddus chevron

In [ ]:
tx[tx['clean_name'].isna()]

Empty DataFrame
Columns: [full_name, reported_state, id, transactor_type, last_name, name_suffix, first_name, name_prefix, name_preferred, ein, transactor_type_specific, phone_number, clean_name]
Index: []

In [ ]:
tx = tx[['clean_name', 'transactor_type']]
tx

                                  clean_name transactor_type
0                               not employed            <NA>
1                              self-employed            <NA>
2                                assist2sell            <NA>
3                     distinctionjewelry.com            <NA>
4                     hendrick health system            <NA>
...                                      ...             ...
18066824                    sirloin stockade    Organization
18066825                   logan's roadhouse    Organization
18066826                      tuscany market    Organization
18066827  williamson county republican women    Organization
18066828                    broaddus chevron    Organization

[18066829 rows x 2 columns]

In [17]:
tx['transactor_type'].unique()

<StringArray>
[<NA>, 'Individual', 'Organization']
Length: 3, dtype: string

In [34]:
pd_na = str(tx.iloc[0]['transactor_type'])

In [35]:
pd_na

'<NA>'

In [36]:
import numpy as np
def replace_na(t_type, na=pd_na):
  if str(t_type) == pd_na:
    return np.nan
  else:
    return t_type

In [37]:
tx['transactor_type'] = tx['transactor_type'].apply(replace_na)

/tmp/ipython-input-681036884.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tx['transactor_type'] = tx['transactor_type'].apply(replace_na)

In [38]:
tx

                                  clean_name transactor_type
0                               not employed             NaN
1                              self-employed             NaN
2                                assist2sell             NaN
3                     distinctionjewelry.com             NaN
4                     hendrick health system             NaN
...                                      ...             ...
18066824                    sirloin stockade    Organization
18066825                   logan's roadhouse    Organization
18066826                      tuscany market    Organization
18066827  williamson county republican women    Organization
18066828                    broaddus chevron    Organization

[18066829 rows x 2 columns]

In [39]:
non_annot_tx = tx[tx['transactor_type'].isna()].copy()

In [40]:
annot_tx = tx[tx['transactor_type'].notna()].copy()

In [41]:
non_annot_tx.groupby('transactor_type', dropna=False).size()

transactor_type
NaN    2273892
dtype: int64

In [42]:
annot_tx.groupby('transactor_type', dropna=False).size()

transactor_type
Individual      14768724
Organization     1024213
dtype: int64

In [45]:
import pandas as pd
from google.colab import files

annot_tx.to_parquet('Clean_TX.parquet', index=False)
files.download('Clean_TX.parquet')