In [22]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 100

In [27]:
unlabeled = pd.read_csv("data\\mi_non_annotated_data.csv")
predicted = pd.read_csv("data\\all_states_predicted.csv", names=['predictions'])

C:\Users\Drew\AppData\Local\Temp\ipykernel_16672\3167790809.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  unlabeled = pd.read_csv("data\\mi_non_annotated_data.csv")

In [ ]:

unlabeled

                                   Unnamed: 0 full_name  label
0                                 butzel long         0    NaN
1                           pavilion township         0    NaN
2                           doozies ice cream         0    NaN
3                alwood landscaping & nursery         0    NaN
4                        explore chiropractic         0    NaN
...                                       ...       ...    ...
1956666  michigan department of state               NaN    NaN
1956667  squarespace                                NaN    NaN
1956694  memo entry                                 NaN    NaN
1956696  the cte to elect jennifer johnsen fo       NaN    NaN
1956831                      douglas waggener       NaN    NaN

[282818 rows x 3 columns]

In [10]:
predicted

        predictions
0               0.0
1               0.0
2               0.0
3               0.0
4               0.0
...             ...
282821          0.0
282822          0.0
282823          0.0
282824          0.0
282825          0.0

[282826 rows x 1 columns]

In [11]:
unlabeled['predicted'] = predicted['predictions']

In [12]:
unlabeled[unlabeled['predicted'] == 0].sample(100)

                                  Unnamed: 0 full_name  label  predicted
35592   ali ^                                      NaN    NaN        0.0
1026    zielinski                                  NaN    NaN        0.0
109418  kopson                                     NaN    NaN        0.0
272549  semak                                      NaN    NaN        0.0
3462                         beaumont health       NaN    NaN        0.0
246339                      ufcw local no. 5       NaN    NaN        0.0
149266  sargeant                                   NaN    NaN        0.0
55610                    not employed-abrams       NaN    NaN        0.0
142640  sohal ^                                    NaN    NaN        0.0
50964   mccallister                                NaN    NaN        0.0
204596  chilcott                                   NaN    NaN        0.0
114798  lucitte                                    NaN    NaN        0.0
94694   vendramini ^                               NaN    NaN        0.0
147561                         tri-cities cu       NaN    NaN        0.0
51230   brininstool ^                              NaN    NaN        0.0
259935  novello                                    NaN    NaN        0.0
111188  marino betz                                NaN    NaN        0.0
203000  jupiter                                    NaN    NaN        0.0
207195  digre                                      NaN    NaN        0.0
31278   moorerdonald                               NaN    NaN        0.0
123660  birn                                       NaN    NaN        0.0
47044   riccobono                                  NaN    NaN        0.0
49026   grein                                      NaN    NaN        0.0
265477                            linda bont       NaN    NaN        0.0
96532   katty ^                                    NaN    NaN        0.0
86304   adermatt                                   NaN    NaN        0.0
43872   mcadams ^                                  NaN    NaN        0.0
130889  cupp ^                                     NaN    NaN        0.0
32508   wehr ^                                     NaN    NaN        0.0
78822   visperas ^                                 NaN    NaN        0.0
48202   hoepner                                    NaN    NaN        0.0
79959   empie ^                                    NaN    NaN        0.0
86630   beschoner                                  NaN    NaN        0.0
203385  andersen beth                              NaN    NaN        0.0
100391  freker                                     NaN    NaN        0.0
98128   spooner ^                                  NaN    NaN        0.0
42010   baker iiiharold                            NaN    NaN        0.0
77130   mangrulkar                                 NaN    NaN        0.0
159422  skudlarek                                  NaN    NaN        0.0
208404  kahlstorf                                  NaN    NaN        0.0
141973  conrad zaske ms.^                          NaN    NaN        0.0
2129    lemerand                                   NaN    NaN        0.0
168628  steanburg                                  NaN    NaN        0.0
79852   bonaudo ^                                  NaN    NaN        0.0
203881  jacob steven                               NaN    NaN        0.0
22868   deveja                                     NaN    NaN        0.0
23156   eckerdt                                    NaN    NaN        0.0
84610   bohmer                                     NaN    NaN        0.0
261665                         shannon price       NaN    NaN        0.0
41908   woodsshawn                                 NaN    NaN        0.0
33796   hooper ^                                   NaN    NaN        0.0
63008   karlson                                    NaN    NaN        0.0
5856    piotrowski                                 NaN    NaN        0.0
58277   consumers energy employees for bette       NaN    NaN        0.0
99403   giampaola ^                                NaN    NaN        0.0
61548   amison                                     NaN    NaN        0.0
168413  kreamalmeyer                               NaN    NaN        0.0
75153   miltko                                     NaN    NaN        0.0
15672   stengerjimmy                               NaN    NaN        0.0
100438  heikka                                     NaN    NaN        0.0
254229  bageris mr^                                NaN    NaN        0.0
239710  palacios rodrig                            NaN    NaN        0.0
39621   sprinkle                                   NaN    NaN        0.0
139154               galloway & collens pllc       NaN    NaN        0.0
11917   goodnough                                  NaN    NaN        0.0
77047   klinkenberger                              NaN    NaN        0.0
48539                   the peterson company       NaN    NaN        0.0
235566  canchola                                   NaN    NaN        0.0
124357  nostrant mr^                               NaN    NaN        0.0
6332    caudill                                    NaN    NaN        0.0
4420    hoyt                                       NaN    NaN        0.0
31470   meedercolt                                 NaN    NaN        0.0
94453   trudo ^                                    NaN    NaN        0.0
273812  larges                                     NaN    NaN        0.0
228664  shayna                                     NaN    NaN        0.0
140677  dinsmoore ^                                NaN    NaN        0.0
15749   dilaura                                    NaN    NaN        0.0
34018   mullaney ^                                 NaN    NaN        0.0
138319  major ^                                    NaN    NaN        0.0
16384   ganum                                      NaN    NaN        0.0
14916                               rite aid       NaN    NaN        0.0
16885   erb                                        NaN    NaN        0.0
206612  budras                                     NaN    NaN        0.0
39161   kovatch                                    NaN    NaN        0.0
125220  stablein ^                                 NaN    NaN        0.0
34632   glaza mr.^                                 NaN    NaN        0.0
89124   kelpinski                                  NaN    NaN        0.0
215419                        pollicella ins       NaN    NaN        0.0
92816           busy bee's embroidery  gifts       NaN    NaN        0.0
149194  fazal                                      NaN    NaN        0.0
59295                          ghina seblani       NaN    NaN        0.0
211116                 mitchell dobrzelewski       NaN    NaN        0.0
186590  van deusen                                 NaN    NaN        0.0
72562   smith mr.^iii                              NaN    NaN        0.0
187421  cossey ii                                  NaN    NaN        0.0
52376   di benedetto                               NaN    NaN        0.0
156709        executive property maintenance       NaN    NaN        0.0
61643   provencher-hood                            NaN    NaN        0.0
2836    woolley                                    NaN    NaN        0.0
164157  hickerty                                   NaN    NaN        0.0